### Working with Numpy - for Mathematical operations

In [2]:
import numpy as np

In [106]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [107]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(type(b))
print(b.shape)
print(b[0])
print(b[0][0])

[[1]
 [2]
 [3]
 [4]
 [5]]
<class 'numpy.ndarray'>
(5, 1)
[1]
1


In [108]:
c = np.array([[1,2,3],[4,5,6]])
print(type(c))
print(c.shape)
print(c)

<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [4 5 6]]


In [109]:
print(c[0,1])

2


In [110]:
# Create ZEROS,ONES, Custom Arrays

In [111]:
a = np.zeros((3,3))

In [112]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [113]:
print(a.shape)

(3, 3)


In [114]:
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [115]:
# Array of some constants

In [116]:
c = np.full((3,2),5)

In [117]:
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [118]:
# Identity Matrix - Size(square) matrix

In [119]:
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [120]:
# Random Matrix

In [121]:
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0.50522416 0.22102269 0.38723015]
 [0.42401582 0.50928552 0.45108486]]


In [122]:
print(randomMatrix[:,1])

[0.22102269 0.50928552]


In [123]:
print(randomMatrix[:,1].shape)

(2,)


In [124]:
print(randomMatrix[1,1:])

[0.50928552 0.45108486]


In [125]:
print(randomMatrix[1,1:3])

[0.50928552 0.45108486]


In [126]:
randomMatrix[1,1:3] = 1 # Slicing
print(randomMatrix)

[[0.50522416 0.22102269 0.38723015]
 [0.42401582 1.         1.        ]]


In [127]:
## Set some rows and columns with any values

In [128]:
z = np.zeros((3,3), dtype = np.int64)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [129]:
z[1,:] = 5
z[:,-1] = 7  # last column is also selected as -1
print(z)

[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [130]:
# Data Types

In [131]:
print(z.dtype)

int64


In [132]:
# Mathematical Operation In Numpy

In [133]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [134]:
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [135]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [136]:
# element wise product

In [137]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [138]:
# element wise division

In [139]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [140]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [141]:
# Matrix Multiplication / Dot Products

In [142]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [143]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [144]:
# Multiplication(Dot Product) of Vectors - Scalars

In [145]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [165]:
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [166]:
print(sum(a))

[ 2  6 12 20]


In [167]:
print(a.sum())

40


In [168]:
print(x)

[[1 2]
 [3 4]]


In [169]:
print(np.sum(x))

10


In [170]:
print(np.sum(x,axis = 0))

[4 6]


In [171]:
print(np.sum(x,axis = 1))

[3 7]


In [172]:
# Stacking of arrays

In [173]:
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [174]:
b = b**2
print(b)

[[       1      256     6561    65536]
 [       1    65536 43046721        0]]


In [188]:
a = np.array([1,2,3,4])
b = np.array([1,4,9,16])

In [189]:
#np.stack((a,b),axis = 1)

In [191]:
print(a.shape)
print(b.shape)
a = np.stack((a,b),axis = 0)
print(a)

(4,)
(4,)
[[ 1  2  3  4]
 [ 1  4  9 16]]


In [177]:
# Reshape a Numpy array

In [192]:
a = a.reshape(4,2)
print(a)
print(a.shape)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
(4, 2)


In [194]:
a = a.reshape((8,1))
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [196]:
a = a.reshape((8,))
print(a)

[ 1  2  3  4  1  4  9 16]


In [197]:
a = a.reshape((4,-1)) # when you don't want to specify the number of columns
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [198]:
# similarily when you dont wish to specify the number of rows
a = a.reshape((-1,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
