## Some more numpy functions - Statistics

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4],[7,6,2,0]])

In [4]:
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [5]:
print(np.min(a))

0


In [6]:
print(np.min(a,axis = 0))

[1 2 2 0]


In [7]:
print(np.min(a,axis = 1))

[1 0]


In [8]:
b = np.array([1,2,3,4,5])

In [10]:
mean = sum(b)/5
print(mean)

3.0


In [11]:
print(np.mean(b))

3.0


In [12]:
print(np.mean(a,axis = 0))

[4.  4.  2.5 2. ]


In [13]:
print(np.mean(a,axis = 1))

[2.5  3.75]


In [14]:
c = np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [15]:
# difference between mean and average

In [16]:
# average -- is weighted

In [17]:
print(np.mean(c))

2.4


In [18]:
w = np.array([1,2,3,4,5])
print(np.average(c,weights = w))

2.066666666666667


In [19]:
wt2 = np.array([1,1,1,1,1])
print(np.average(c,weights = wt2))

2.4


In [20]:
#Standard Deviation

In [22]:
u = np.mean(c)

In [25]:
myStd = np.sqrt(np.mean((c-u)**2))

In [26]:
print(myStd)

1.854723699099141


In [27]:
dev = np.std(c)
print(dev)

1.854723699099141


In [28]:
#Variance
print(myStd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
