## Numpy Random Module

rand : Random values in a given shape
randn : Return a sample (or samples) from the "standard normal" distribution
randint : Return random integers from low(inclusive) to high(exclusive)
random : Return random floats in the half-open interval 0.0 inclusive to 1.0 exclusive
choice : Generates a random sample from a given 1-D Array
Shuffle : Shuffles the contents of a sequence

In [2]:
import numpy as np

In [6]:
# might be helpful to generate the indices itself
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [7]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [11]:
np.random.shuffle(a)
print(a)

[14  8  7 11 13 12 10  9  5  6]


In [29]:
np.random.seed(1)
a = np.random.rand(2,3)
print(a)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]


In [35]:
np.random.seed(1)
a = np.random.randn(2,3)
print(a)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]


In [36]:
a = np.random.randint(56,58,2)
print(a)

[56 57]


In [42]:
np.random.seed(2)
element = np.random.choice([45,67,89,12])
print(element)

45
